import Link from "next/link";
import { MessageSquareText } from "lucide-react";
import DoctorShell from "@/components/DoctorShell";
import DoctorQueryActions from "@/components/DoctorQueryActions";
import { serverApi } from "@/lib/server-api";
export const dynamic="force-dynamic";
const category={ADMINISTRATIVE:"General / administrative",MEDICATION:"Medication-related",SYMPTOM_CONCERN:"Patient concern / symptoms"};
export default async function QueriesPage(){const patients=await serverApi.patients();const data=(await Promise.all(patients.map(async p=>({p,d:await serverApi.patient360(p.id)})))).flatMap(({p,d})=>d.open_queries.map(q=>({p,q})));return <DoctorShell>
<p className="onko-eyebrow text-onko-teal">Patient communication</p><h1 className="mt-2 text-[44px] font-bold tracking-tight">Queries</h1><p className="mt-2 max-w-3xl text-[16px] leading-7 text-onko-muted">Active patient queries requiring care-team review. Once resolved, they leave this queue and remain available in the patient history.</p>
<div className="mt-7 grid gap-4">{data.length?data.map(({p,q})=><article key={q.id} className="onko-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-onko-softteal text-onko-teal"><MessageSquareText size={21}/></span><div><Link href={"/doctor/patients/"+p.id} className="text-[20px] font-bold hover:text-onko-teal">{p.name}</Link><p className="mt-1 text-[13px] text-onko-muted">{q.channel} · {q.status}</p></div></div><span className="onko-chip bg-onko-softteal text-onko-teal">{category[q.category]}</span></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-xl bg-onko-surface p-5"><p className="text-[12px] font-bold uppercase tracking-wide text-onko-muted">Original message</p><p className="mt-2 text-[15px] leading-6">{q.text}</p></div><div className="rounded-xl bg-onko-softteal/60 p-5"><p className="text-[12px] font-bold uppercase tracking-wide text-onko-muted">Organized summary</p><p className="mt-2 text-[15px] leading-6">{q.summary}</p><p className="mt-3 text-[13px] text-onko-muted">Route: {q.route_to.replaceAll("_"," ")}</p></div></div><DoctorQueryActions queryId={q.id} initialStatus={q.status}/></article>):<div className="onko-card p-6 text-[15px] text-onko-muted">No active queries requiring review.</div>}</div>
</DoctorShell>}
