import {CalendarDays,ClipboardCheck,FileText,Pill,Stethoscope,Target} from "lucide-react";
import PatientShell from "@/components/PatientShell";
import PrintSummaryButton from "@/components/PrintSummaryButton";
import { serverApi } from "@/lib/server-api";
import {currentPatientId} from "@/lib/patient-session";
import {fmtDate} from "@/lib/format";
export const dynamic="force-dynamic";
export default async function Summary({searchParams}:{searchParams?:{id?:string}}){const ID=currentPatientId(searchParams);const d=await serverApi.patient360(ID,{role:"patient",userId:ID}),p=d.patient;const groups=[["Medication","MEDICATION",Pill],["Treatments","TREATMENT",Stethoscope],["Investigations","INVESTIGATION",ClipboardCheck],["Appointments","APPOINTMENT",CalendarDays],["Milestones","MILESTONE",Target]] as const;return <PatientShell patient={p}><div className="mx-auto max-w-5xl print:max-w-none"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="onko-eyebrow">Portable care summary</p><h1 className="mt-1 text-[30px] font-bold sm:text-[38px]">{p.name}&apos;s Care Summary</h1><p className="mt-2 text-[14px] text-onko-muted">An organized view of information already recorded in OnKo for continuity of care.</p></div><PrintSummaryButton/></div>
 <section className="onko-card mt-5 grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-[11px] font-bold uppercase text-onko-muted">Journey state</p><p className="mt-1 text-[15px] font-bold capitalize">{p.journey_state.replaceAll("_"," ").toLowerCase()}</p></div><div><p className="text-[11px] font-bold uppercase text-onko-muted">Regimen</p><p className="mt-1 text-[15px] font-bold">{p.regimen_label}</p></div><div><p className="text-[11px] font-bold uppercase text-onko-muted">Cycle</p><p className="mt-1 text-[15px] font-bold">{p.cycle_current} of {p.cycle_total}</p></div><div><p className="text-[11px] font-bold uppercase text-onko-muted">Preferred language</p><p className="mt-1 text-[15px] font-bold">{p.preferred_language}</p></div></section>
 <div className="mt-5 grid gap-4">{groups.map(([title,type,Icon])=>{const items=d.timeline.filter(e=>e.type===type);return <section key={type} className="onko-card p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-onko-softteal text-onko-teal"><Icon size={19}/></span><h2 className="text-[19px] font-bold">{title}</h2></div><div className="mt-4 grid gap-2">{items.length?items.map(e=><div key={e.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-onko-surface p-3"><div><strong className="text-[14px]">{e.title}</strong><p className="mt-1 text-[12px] text-onko-muted">{fmtDate(e.scheduled_at)} · {e.source}</p></div><span className="onko-chip bg-white text-onko-muted">{e.status.replaceAll("_"," ").toLowerCase()}</span></div>):<p className="text-[13px] text-onko-muted">No items recorded.</p>}</div></section>})}</div>
 <section className="onko-card mt-4 p-5"><div className="flex items-center gap-3"><FileText size={19} className="text-onko-teal"/><h2 className="text-[19px] font-bold">Available records</h2></div><div className="mt-3 grid gap-2">{d.reports.map(r=><div key={r.id} className="rounded-xl bg-onko-surface p-3"><strong className="text-[14px]">{r.title}</strong><p className="mt-1 text-[12px] text-onko-muted">Uploaded {fmtDate(r.uploaded_at)}</p></div>)}</div></section>
 <p className="mt-5 text-[12px] leading-5 text-onko-muted">This summary organizes recorded care information. It does not provide clinical interpretation, diagnosis or treatment recommendations.</p>
 </div></PatientShell>}